/*
 * OpenAPI Petstore
 *
 * This spec is mainly for testing Petstore server and contains fake endpoints, models. Please do not use this for any other purpose. Special characters: \" \\
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Org.OpenAPITools.Client;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TestResult
    /// </summary>
    [DataContract(Name = "TestResult")]
    public partial class TestResult : IEquatable<TestResult>
    {

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public Option<TestResultCode> Code { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="TestResult" /> class.
        /// </summary>
        /// <param name="code">code.</param>
        /// <param name="uuid">Result unique identifier.</param>
        /// <param name="data">list of named parameters for current message.</param>
        public TestResult(Option<TestResultCode> code = default, Option<string> uuid = default, Option<Dictionary<string, string>> data = default)
        {
            // to ensure "uuid" (not nullable) is not null
            if (uuid.IsSet && uuid.Value == null)
            {
                throw new ArgumentNullException("uuid isn't a nullable property for TestResult and cannot be null");
            }
            // to ensure "data" (not nullable) is not null
            if (data.IsSet && data.Value == null)
            {
                throw new ArgumentNullException("data isn't a nullable property for TestResult and cannot be null");
            }
            this.Code = code;
            this.Uuid = uuid;
            this.Data = data;
        }

        /// <summary>
        /// Result unique identifier
        /// </summary>
        /// <value>Result unique identifier</value>
        [DataMember(Name = "uuid", EmitDefaultValue = false)]
        public Option<string> Uuid { get; set; }

        /// <summary>
        /// list of named parameters for current message
        /// </summary>
        /// <value>list of named parameters for current message</value>
        [DataMember(Name = "data", EmitDefaultValue = false)]
        public Option<Dictionary<string, string>> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TestResult {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  Uuid: ").Append(Uuid).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TestResult);
        }

        /// <summary>
        /// Returns true if TestResult instances are equal
        /// </summary>
        /// <param name="input">Instance of TestResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TestResult input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Code == input.Code ||
                    this.Code.Equals(input.Code)
                ) && 
                (
                    this.Uuid == input.Uuid ||
                    
                    this.Uuid.Equals(input.Uuid)
                ) && 
                (
                    this.Data == input.Data ||
                    this.Data.IsSet && this.Data.Value != null &&
                    input.Data.IsSet && input.Data.Value != null &&
                    this.Data.Value.SequenceEqual(input.Data.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Code.IsSet)
                {
                hashCode = (hashCode * 59) + this.Code.Value.GetHashCode();
                }
                if (this.Uuid.IsSet && this.Uuid.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Uuid.Value.GetHashCode();
                }
                if (this.Data.IsSet && this.Data.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Data.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
